### ISSUE TITLE
Couldn't initiate registration: SyntaxError: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by remivern** [davidearl/webauthn#7] opened 2019-03-12 10:45 UTC
Hello,

Thanks for this very good job!
I'am trying to understand the code but when I try to implement it on my server I have the following message: Couldn't initiate registration: SyntaxError: Unexpected token < in JSON at position 1
The /.users is created with 777chmod. No json file is present in the /.users directory

URL: http://35.190.191.90/webauthn/example/index.php

Thanks for you time and your help...
Rémi

**Comment by davidearl** [comment] 2019-03-12 12:08
It looks like if the users directory is empty and you try to "log in" before registering, the example code gets this error. I'll fix this shortly by producing a more meaningful error message, but you would normally want to register before trying to "log in" - if there are no registrations, attempts to log in will inevitably fail.

**Comment by remivern** [comment] 2019-03-12 12:39
Thanks for your quick answer!

I have already tried using User Registration before. Sadly, the error message is couldn't **initiate registration**: SyntaxError: Unexpected token < in JSON at position 1

When i try to log in before regristering i have: couldn't **initiate login**: SyntaxError: Unexpected token < in JSON at position 1

I feel like I can not register :-(

**Comment by davidearl** [comment] 2019-03-12 13:12
Ok, I’ll look further at this this afternoon

**Comment by davidearl** [comment] 2019-03-12 17:09
Sorry, I didn't look closely enough at the error previously. So the problem is index.php is not in your document root, so when the Ajax callback happens it returns the default Apache server page rather than the JSON.

The example assumes this is on a dedicated (virtual) host so you should be able to find index.php in http://35.190.191.90/ along with the whole webauthn directory as checked out from github, and CBOREncode as checked out from github. Rather than copy webauthn/example/index.php up two levels, I suggest you link to it if your Apache setup allows links, or if not put an index.php in the top level which includes the one in example.

If http://35.190.191.90/ can't be dedicated to webauthn, you'll need to change the includes at the top of example, to be where you put the files, as $_SERVER['DOCUMENT_ROOT'] assumes it is at the top level.

So if, for example, you put it in "mywebauthn" and your document root is /var/www, then you'd have

```
   /var/www/mywebauthn
      index.php [link to index.php below]
      webauthn
             src
                   ...
             example
                    index.php
      CBOREncode
        ...
```

and change the four includes in index.php to add the mywebauthn directory after `$_SERVER['DOCUMENT_ROOT'].'`

I have checked that an install from scratch still works, and it does. I also just checked in a change to index.php to be clearer about where .users is if it can't be created, though this is not your initial problem.

**Comment by davidearl** [comment] 2019-03-12 17:14
By the way, I know this is just as an example, but it is really rather pointless if you don't use https (you can get free certificates from LetsEncrypt), and you have left Indexes on on your Apache setup so all the files are readable externally including the .users directory. .users would ideally be elsewhere anyway. You certainly don't want a live version to do this!

**Comment by remivern** [comment] 2019-03-26 12:48
Hello! 
Sorry, I really forgot to answer you. It's work fine !!!
I really enjoyed your help !!!

Rémi

**Comment by geraldkrug** [comment] 2019-03-27 21:07
I got the webauthn result written into each fingerprint images exif copyright tag...
CopyrightNotice Copyright /a-finger/img/6865f27ef75723939f37d9da83cc6c55 The GDK Group

**Comment by davidearl** [comment] 2019-03-27 21:10
Sorry @geraldkrug, I have no idea what you mean, and I don't see what it has to do with this issue. Please can you elucidate, in a new issue if that's what it is.

**Comment by davidearl** [comment] 2019-03-27 21:10
Thank you @remivern . Closing this now.

**Closed by davidearl** 2019-03-27 21:10 UTC
Labels: bug
